"""GitHub Actions mode: the queue lives in a private repository and a workflow posts.

Your computer can be off. The approval moment is marking a post `queued` and
pushing it, not a button at posting time: on GitHub Free, Pro and Team, required
reviewers for workflow runs are only available in public repositories, and a
queue of unpublished posts belongs in a private one.
"""
from __future__ import annotations

import datetime as dt
from pathlib import Path
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

LOCAL_START_HOUR = 6   # first local hour in which the workflow looks for due posts
LOCAL_END_HOUR = 22    # last local hour (inclusive)


def local_timezone() -> str:
    """The IANA name of this machine's timezone, read from /etc/localtime."""
    try:
        target = Path("/etc/localtime").resolve()
        parts = target.parts
        if "zoneinfo" in parts:
            name = "/".join(parts[parts.index("zoneinfo") + 1:])
            ZoneInfo(name)
            return name
    except (OSError, ZoneInfoNotFoundError, ValueError):
        pass
    return "UTC"


def utc_hours(tz_name: str, start: int = LOCAL_START_HOUR, end: int = LOCAL_END_HOUR) -> list[int]:
    """UTC hours that cover local hours start..end in both winter and summer time."""
    tz = ZoneInfo(tz_name)
    hours: set[int] = set()
    for month in (1, 7):
        for local_hour in range(start, end + 1):
            local = dt.datetime(2026, month, 15, local_hour, tzinfo=tz)
            hours.add(local.astimezone(dt.UTC).hour)
    return sorted(hours)


def cron_hours(hours: list[int]) -> str:
    """[4, 5, 6, 20, 21] -> '4-6,20-21'."""
    ranges: list[str] = []
    start = prev = hours[0]
    for hour in hours[1:] + [None]:
        if hour is not None and hour == prev + 1:
            prev = hour
            continue
        ranges.append(f"{start}-{prev}" if start != prev else str(start))
        if hour is not None:
            start = prev = hour
    return ",".join(ranges)


def runs_per_month(hours: list[int], per_hour: int = 2) -> int:
    return len(hours) * per_hour * 31


PUBLISH_WORKFLOW = """\
# Posts what is due from queue/. Generated by `linkedin-publisher init --github`.
#
# Runs every 30 minutes between {local_start}:00 and {local_end}:59 {tz} (the
# cron below is in UTC and covers both winter and summer time). A post goes out
# at the first run after its slot. GitHub sometimes starts scheduled runs late;
# a post that is more than grace_minutes late is not posted.
#
# Actions minutes: about {runs} runs a month. Even if every run counted as a full
# minute, that is {runs} of the 2,000 free minutes for private repositories on
# GitHub Free.
name: linkedin-publisher

on:
  schedule:
    - cron: "0,30 {cron_hours} * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: linkedin-publisher
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      TZ: {tz}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install "linkedin-publisher @ git+https://github.com/Vinix24/linkedin-publisher@v{version}"
      - name: Write the token file from the secret
        env:
          LINKEDIN_TOKENS: ${{{{ secrets.LINKEDIN_TOKENS }}}}
        run: printf '%s' "$LINKEDIN_TOKENS" > .linkedin-tokens.json
      - name: Post what is due
        env:
          LINKEDIN_CLIENT_ID: ${{{{ secrets.LINKEDIN_CLIENT_ID }}}}
          LINKEDIN_CLIENT_SECRET: ${{{{ secrets.LINKEDIN_CLIENT_SECRET }}}}
        run: linkedin-publisher publish --post
      - name: Commit the moved post and its receipt
        if: always()
        run: |
          rm -f .linkedin-tokens.json
          git config user.name "linkedin-publisher"
          git config user.email "linkedin-publisher@users.noreply.github.com"
          git add -A queue published .receipts
          if ! git diff --cached --quiet; then
            git commit -m "linkedin-publisher: posted"
            git pull --rebase
            git push
          fi
"""

TOKEN_CHECK_WORKFLOW = """\
# Fails once a day during the last {warn_days} days before the LinkedIn token expires,
# so GitHub tells you before posting stops. Renew with:
#   linkedin-publisher auth && gh secret set LINKEDIN_TOKENS < .linkedin-tokens.json
name: linkedin-token-check

on:
  schedule:
    - cron: "0 {check_hour} * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install "linkedin-publisher @ git+https://github.com/Vinix24/linkedin-publisher@v{version}"
      - env:
          LINKEDIN_TOKENS: ${{{{ secrets.LINKEDIN_TOKENS }}}}
        run: |
          printf '%s' "$LINKEDIN_TOKENS" > .linkedin-tokens.json
          linkedin-publisher status --fail-days {warn_days}
"""

GITIGNORE = """\
# GitHub Actions mode: the queue, published posts and receipts ARE committed.
# Receipts must stay in git, they are what stops a post from going out twice.
.env
.linkedin-tokens.json
.publisher.lock
publisher.log
schedule.log
.last-check
"""


def workflows(tz_name: str, version: str, warn_days: int = 7) -> dict[str, str]:
    hours = utc_hours(tz_name)
    check_hour = dt.datetime(2026, 1, 15, 9, tzinfo=ZoneInfo(tz_name)).astimezone(dt.UTC).hour
    return {
        ".github/workflows/linkedin-publisher.yml": PUBLISH_WORKFLOW.format(
            local_start=LOCAL_START_HOUR, local_end=LOCAL_END_HOUR, tz=tz_name,
            cron_hours=cron_hours(hours), runs=runs_per_month(hours), version=version),
        ".github/workflows/linkedin-token-check.yml": TOKEN_CHECK_WORKFLOW.format(
            check_hour=check_hour, warn_days=warn_days, version=version),
    }
